# Generated by Django 4.1.4 on 2023-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('establish', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('branches', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('facilities', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
