# Generated by Django 4.1.4 on 2023-01-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0004_cd_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cd',
        ),
    ]
