# Generated by Django 4.1.4 on 2023-01-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0006_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Info',
        ),
    ]
