# Generated by Django 4.1.4 on 2023-01-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0007_rename_profile_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
