# Generated by Django 4.1.4 on 2023-01-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0008_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gender',
        ),
    ]
