# Generated by Django 4.1.6 on 2023-02-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0021_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(),
        ),
    ]
