# Generated by Django 4.1.6 on 2023-02-03 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoTour', '0022_info_gender_alter_info_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
    ]
